DROP TABLE IF EXISTS "Buildings";
CREATE TABLE "Buildings" ("buildingId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "building" TEXT);
DROP TABLE IF EXISTS "CoRequisites";
CREATE TABLE "CoRequisites" ("crId" INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL , "sectionId" INTEGER, "subject" TEXT,  "courseNum" TEXT, "crCourseId" INTEGER);
DROP TABLE IF EXISTS "Courses";
CREATE TABLE "Courses" ("courseId" INTEGER PRIMARY KEY AUTOINCREMENT   NOT NULL , "subjectId" INTEGER, "courseNum" TEXT,  "credits" INTEGER);
DROP TABLE IF EXISTS "Instructors";
CREATE TABLE "Instructors" ("instructorId" INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL , "firstName" TEXT, "lastName" TEXT);
DROP TABLE IF EXISTS "PreRequisites";
CREATE TABLE "PreRequisites" ("prId" INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL , "sectionId" INTEGER, "subject" TEXT,  "courseNum" TEXT, "prCourseId" INTEGER);
DROP TABLE IF EXISTS "ScheduleTypes";
CREATE TABLE "ScheduleTypes" ("scheduleTypeId" INTEGER PRIMARY KEY AUTOINCREMENT   NOT NULL , "scheduleType" TEXT);
DROP TABLE IF EXISTS "SectionCombinations";
CREATE TABLE "SectionCombinations" ("scId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "sectionId" INTEGER, "subject" TEXT, "courseNum" TEXT, "sectionNum" TEXT, "sectionSpecific" TEXT, "scSectionId" INTEGER);
DROP TABLE IF EXISTS "SectionLocations";
CREATE TABLE "SectionLocations" ("sectionLocationId" INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL , "sectionId" INTEGER, "roomNum" TEXT, "buildingId" INTEGER);
DROP TABLE IF EXISTS "SectionTimes";
CREATE TABLE "SectionTimes" ("sectionTimeId" INTEGER PRIMARY KEY AUTOINCREMENT   NOT NULL , "sectionId" INTEGER, "day" TEXT, "timeStart" TEXT, "timeEnd" TEXT);
DROP TABLE IF EXISTS "Sections";
CREATE TABLE "Sections" ("sectionId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "termId" INTEGER, "CRN" TEXT,"courseId" INTEGER, "sectionNum" TEXT, "title" TEXT, "scheduleTypeId" INTEGER, "instructorId" INTEGER, "meetingStart" TEXT, "meetingEnd" TEXT, "enrlCap" INTEGER, "enrlAct" INTEGER, "waitCap" INTEGER, "waitAct" INTEGER, "isEXL" INTEGER, "isETIE" INTEGER, "isTransferIN" INTEGER, "isCanceled" INTEGER, "isOnline" INTEGER, "isSIA" INTEGER, "textBookLink" TEXT,"CRNLink" TEXT,"notes" TEXT);
DROP TABLE IF EXISTS "Subjects";
CREATE TABLE "Subjects" ("subjectId" INTEGER PRIMARY KEY AUTOINCREMENT   NOT NULL , "subject" TEXT);
DROP TABLE IF EXISTS "Terms";
CREATE TABLE "Terms" ("termId" INTEGER PRIMARY KEY AUTOINCREMENT    NOT NULL , "quarter" TEXT, "year" INTEGER);
